### PR TITLE
Feature: GET products from mock server

### PR DESCRIPTION
**Pull request by bharati-21**
- This PR has the following features:
   - Product context and reducers to fetch products from mock server
   - Display loading, error states
   - Map through the products and display product data on the products page
  

image

### CODE REVIEW

**Review by shashikantmaurya0007 — APPROVED** [review]
1.you have done the best use of destructuring.
2.Good to see you have created actions object.
3.very well structured code

**Review by jeetbhalani15 — APPROVED** [review]
-Good to see, using useReducer to fetch data.
-Nice use of tabs for sorting.
-Clean & readable Code.

**Comment by bharati-21** [comment]
> 1.you have done the best use of destructuring. 2.Good to see you have created actions object. 3.very well structured code

Thank you for your review!

**Comment by bharati-21** [comment]
> -Good to see, using useReducer to fetch data. -Nice use of tabs for sorting. -Clean & readable Code.



> -Good to see, using useReducer to fetch data. -Nice use of tabs for sorting. -Clean & readable Code.

Thank you for your review!

**Review by anuj-kumary — APPROVED** [review]
Everything looks good to me. The code is readable and well-indented. The folder structure is good too.

**Comment by bharati-21** [comment]
> Everything looks good to me. The code is readable and well-indented. The folder structure is good too.

Thank you for your review!

**Pull request merged**
