### PR TITLE
Refactor: Categories and Top picks on the landing page

### PR DESCRIPTION
**Pull request by bharati-21**
This PR includes the following refactors:
- Users can click on any of the categories listed. It navigates to the products listing page with products filtered based on that category
- Edited the product context to include category state
- Fetch categories when the web app loads
- Added util to fetch categories

### CODE REVIEW

**Review by tushargoyal812 — COMMENTED** [review]
code is clean and to the point.
naming convention is very.
liked how you structured files,good work.

**Review by krate27 — APPROVED** [review]
-Things look good. Really liked how you have separated every logic which really is good to read and understand.
- Great use of side effects in entire app, proper practices are followed. 
- Good to merge from my side.

**Comment by bharati-21** [comment]
> code is clean and to the point. naming convention is very. liked how you structured files,good work.

Thank you for your review!

**Comment by bharati-21** [comment]
> -Things look good. Really liked how you have separated every logic which really is good to read and understand.
> 
> * Great use of side effects in entire app, proper practices are followed.
> * Good to merge from my side.

Thank you for your review!

**Pull request merged**
